### ISSUE TITLE
开源社区地图页

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/PWA#13]
## 功能概述

- [ ] 中国地图上显示各地区组织数目
- [ ] 点击某地区后在下方列表显示详细信息

## 后端接口

https://data.kaiyuanshe.cn/documentation#/Organization/get_organizations

**Comment by zhuangbiaowei** [comment]
期待！

**Comment by think-in-universe** [comment]
I'll work on this feature.

**Comment by think-in-universe** [comment]
@TechQuery could you please assign to me?
